#!/usr/bin/env python3
"""
Code Generator for SDN Agent POC
Generates production-ready Perl code for NetMRI SDN modules
"""

import json
from pathlib import Path
from typing import Dict, List
from datetime import datetime


class PerlCodeGenerator:
    """Generate Perl SDN modules"""
    
    def __init__(self, plugin_mappings_file: str, api_data_file: str):
        self.plugin_mappings_file = Path(plugin_mappings_file)
        self.api_data_file = Path(api_data_file)
        self.mappings = None
        self.api_data = None
        self.vendor_name = None
        
    def load_data(self):
        """Load plugin mappings and API data"""
        with open(self.plugin_mappings_file, 'r') as f:
            self.mappings = json.load(f)
        
        with open(self.api_data_file, 'r') as f:
            self.api_data = json.load(f)
        
        # Extract vendor name from title
        title = self.api_data['title']
        self.vendor_name = title.split()[0] if title else "Generic"
        
    def generate_client(self) -> str:
        """Generate SDN Client module"""
        auth_type = self.api_data.get('auth_type', 'api_key')
        auth_header = self.api_data.get('auth_header', 'X-API-Key')
        base_url = self.api_data.get('base_url', '')
        
        code = f"""package NetMRI::HTTP::Client::{self.vendor_name};

use strict;
use warnings;
use NetMRI::LoggerShare;
use NetMRI::HTTP::Client::Generic;
use URI;
use base 'NetMRI::HTTP::Client::Generic';

# Generated by SDN Agent POC - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
# OpenAPI Version: {self.api_data.get('version', '1.0.0')}

my $base_uri = '{base_url}';
my $auth_token_request_header = '{auth_header}';
my $default_api_version = 'v1';

sub new {{
    my $class = shift;
    my %args = @_;
    
    for my $option (qw(api_key fabric_id)) {{
        die "Required parameter $option is not provided" unless ($args{{$option}});
    }}
    
    $args{{base}} = $args{{address}} ? "https://$args{{address}}/api/\\%version\\%/" : $base_uri;
    $args{{auth_token_request_header}} = $auth_token_request_header;
    $args{{requests_per_second}} //= 3;
    
    my $self = $class->SUPER::new(%args);
    $self->{{fabric_id}} = $args{{fabric_id}};
    $self->{{max_iterations_for_paginated_data}} ||= 100;
    
    # Update base URI
    $self->base();
    
    return bless $self, $class;
}}

sub get_throttle_key {{
    my $self = shift;
    return 'Global';
}}

sub too_many_requests_response {{
    my ($self, $res) = @_;
    my $flg = (!$res->{{success}} && $res->{{data}}->{{error}}->{{code}} && $res->{{data}}->{{error}}->{{code}} == 429);
    return $flg;
}}

sub api_request {{
    my ($self, $uri, $api_version, $params) = @_;
    my $res = $self->get($uri, $api_version || $default_api_version, $params);
    
    if ($res->{{success}} && exists($res->{{data}})) {{
        return $res->{{data}};
    }} elsif ($res->{{data}}->{{error}}->{{code}} == 400) {{
        return (undef, $self->{{response}}->{{_content}} || "Bad Request");
    }}
    
    return (undef, $res->{{data}}->{{error}}->{{message}});
}}

sub collect_pages_request {{
    my ($self, $uri, $version, $params) = @_;
    my $res = [];
    my $error = undef;
    my $finished = 0;
    my $max_iterations = $self->{{max_iterations_for_paginated_data}};
    my $cur_iteration = 1;
    
    while (!$error && !$finished) {{
        my ($pool, $err) = $self->api_request($uri, $version, $params);
        $finished = 1;
        
        unless ($err) {{
            push @$res, (ref($pool) eq 'ARRAY' ? @$pool : $pool);
            
            # Check for pagination link in header
            if (ref($self->{{response}}) && $self->{{response}}->header('link') =~ /\\<([^>]+)\\>\\;\\s+rel\\=[\\"\']?next[\\"\']?/) {{
                $finished = 0;
                my $uri = URI->new($1);
                my %query = $uri->query_form;
                $params->{{$_}} = $query{{$_}} foreach keys %query;
            }}
        }} else {{
            $error = $err;
        }}
        
        $cur_iteration++;
        if ($cur_iteration > $max_iterations) {{
            $finished = 1;
            NetMRI::LoggerShare::logWarn("URI: ${{uri}} - iteration limit (${{max_iterations}}) reached");
        }}
    }}
    
    return $error ? (undef, $error) : $res;
}}

"""
        
        # Generate API methods
        code += self._generate_client_methods()
        
        code += "\n1;\n"
        
        return code
    
    def _generate_client_methods(self) -> str:
        """Generate API client methods from endpoints"""
        methods = []
        
        for mapping in self.mappings['mappings']:
            # Find the endpoint in API data
            endpoint = None
            for ep in self.api_data['endpoints']:
                if ep['operation_id'] == mapping['operation_id']:
                    endpoint = ep
                    break
            
            if not endpoint:
                continue
            
            method_name = self._snake_case(endpoint['operation_id'])
            path = endpoint['path']
            params = endpoint['parameters']
            
            # Extract path parameters
            path_params = [p for p in params if p['location'] == 'path']
            query_params = [p for p in params if p['location'] == 'query']
            
            # Build method signature
            perl_params = []
            for param in path_params:
                perl_params.append(f"${param['name']}")
            
            if query_params:
                perl_params.append("$params")
            
            signature = ", ".join(["$self"] + perl_params) if perl_params else "$self"
            
            # Build URI
            uri = path
            for param in path_params:
                uri = uri.replace(f"{{{param['name']}}}", f"${param['name']}")
            
            # Build method documentation
            doc = f"# {endpoint['summary']}\n"
            doc += f"# {endpoint['description']}\n" if endpoint['description'] else ""
            
            if query_params:
                doc += "# Parameters:\n"
                for param in query_params:
                    required = "REQUIRED" if param['required'] else "optional"
                    doc += f"# * {param['name']} ({required})\n"
            
            # Build method body
            method = f"{doc}sub {method_name} {{\n"
            method += f"    my ({signature}) = @_;\n"
            
            if query_params:
                method += "    $params = {} unless ref($params) eq 'HASH';\n"
                for param in query_params:
                    if param.get('default'):
                        method += f"    $params->{{{param['name']}}} //= {param['default']};\n"
            
            method += f"    my $uri = \"{uri}\";\n"
            
            # Determine if paginated
            is_array = endpoint['response_schema'].get('is_array', False)
            if is_array and query_params:
                method += "    return $self->collect_pages_request($uri, undef, $params);\n"
            elif query_params:
                method += "    return $self->api_request($uri, undef, $params);\n"
            else:
                method += "    return $self->api_request($uri);\n"
            
            method += "}\n\n"
            
            methods.append(method)
        
        return "".join(methods)
    
    def generate_server(self) -> str:
        """Generate SDN Server module"""
        code = f"""package NetMRI::SDN::{self.vendor_name};

use strict;
use warnings;
use Encode;
use Data::Dumper;
use NetMRI::SDN::Base;
use base 'NetMRI::SDN::Base';
use Date::Parse;
use NetMRI::Util::Date;
use NetMRI::Util::Network qw (netmaskFromPrefix InetAddr);

# Generated by SDN Agent POC - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

sub new {{
    my $class = shift;
    my $self = $class->SUPER::new(@_);
    $self->{{SaveDevices_unique_fieldname}} = 'Serial';
    $self->{{vendor_name}} = '{self.vendor_name}';
    return bless $self, $class;
}}

sub obtainEverything {{
    my $self = shift;
    my $dev_role = $self->getDeviceRole();
    
    # Collect all data types
    $self->obtainSystemInfo();
    $self->obtainSdnFabricInterface();
    $self->obtainCdpLldp();
    $self->obtainSwitchPort();
    $self->obtainRoute();
    $self->obtainWireless();
}}

"""
        
        # Generate obtain methods based on plugin mappings
        code += self._generate_obtain_methods()
        
        code += "\n1;\n"
        
        return code
    
    def _generate_obtain_methods(self) -> str:
        """Generate data collection methods"""
        methods = []
        
        # Group mappings by plugin
        plugins_map = {}
        for mapping in self.mappings['mappings']:
            plugin = mapping['plugin']
            if plugin not in plugins_map:
                plugins_map[plugin] = []
            plugins_map[plugin].append(mapping)
        
        # Generate getDevices method
        if 'SaveDevices' in plugins_map:
            methods.append(self._generate_get_devices())
        
        # Generate obtainSystemInfo
        if 'SaveSystemInfo' in plugins_map:
            methods.append(self._generate_obtain_system_info())
        
        # Generate obtainSdnFabricInterface
        if 'SaveSdnFabricInterface' in plugins_map:
            methods.append(self._generate_obtain_interfaces())
        
        # Generate obtainCdpLldp
        if 'SaveSdnLldp' in plugins_map:
            methods.append(self._generate_obtain_cdp_lldp())
        
        # Generate obtainSwitchPort
        if 'SaveSdnSwitchPortConfig' in plugins_map:
            methods.append(self._generate_obtain_switch_port())
        
        # Generate obtainRoute
        if 'SaveSdnRoute' in plugins_map:
            methods.append(self._generate_obtain_route())
        
        # Generate obtainWireless
        if 'SaveSdnWirelessSsid' in plugins_map:
            methods.append(self._generate_obtain_wireless())
        
        return "".join(methods)
    
    def _generate_get_devices(self) -> str:
        """Generate getDevices method"""
        return """sub getDevices {
    my $self = shift;
    
    $self->{logger}->debug("getDevices started");
    my $api_helper = $self->getApiClient();
    
    # Get organizations
    my ($organizations, $msg) = $api_helper->get_organizations();
    unless (defined $organizations) {
        $self->{logger}->warn('get_organizations failed: ' . $msg);
        return [];
    }
    
    my @devices;
    
    # Get devices from each organization
    foreach my $org (@$organizations) {
        my ($org_devices, $error) = $api_helper->get_organization_devices($org->{id});
        next if $error;
        
        foreach my $dev (@$org_devices) {
            my %device = (
                SdnControllerId => $api_helper->{fabric_id},
                SdnDeviceDN => "$org->{id}/$dev->{networkId}/$dev->{serial}",
                Name => $dev->{name} || $dev->{serial},
                Serial => $dev->{serial},
                Model => $dev->{model},
                Vendor => $self->{vendor_name},
                SWVersion => $dev->{firmware} || '',
                IPAddress => $dev->{lanIp} || $dev->{wan1Ip} || $dev->{publicIp},
                MACAddress => $dev->{mac} || '',
                modTS => NetMRI::Util::Date::formatDate(str2time($dev->{claimedAt}) || time()),
            );
            
            push @devices, \\%device if $device{IPAddress};
        }
    }
    
    $self->{logger}->debug("Found " . scalar(@devices) . " devices");
    return \\@devices;
}

"""
    
    def _generate_obtain_system_info(self) -> str:
        """Generate obtainSystemInfo method"""
        return """sub obtainSystemInfo {
    my $self = shift;
    
    $self->{logger}->debug("obtainSystemInfo started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    
    # Parse DN to get serial
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($device, $error) = $api_helper->get_device($serial);
    return unless $device;
    
    my %system_info = (
        SdnDeviceDN => $dn,
        Status => 'online',
        SWVersion => $device->{firmware} || '',
        Model => $device->{model} || '',
        Serial => $device->{serial} || '',
    );
    
    $self->saveSystemInfo(\\%system_info);
}

"""
    
    def _generate_obtain_interfaces(self) -> str:
        """Generate obtainSdnFabricInterface method"""
        return """sub obtainSdnFabricInterface {
    my $self = shift;
    
    $self->{logger}->debug("obtainSdnFabricInterface started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($ports, $error) = $api_helper->get_device_switch_ports($serial);
    return unless $ports;
    
    my @interfaces;
    foreach my $port (@$ports) {
        my %interface = (
            SdnDeviceDN => $dn,
            ifIndex => $port->{portId} || '',
            ifName => $port->{name} || "Port $port->{portId}",
            ifOperStatus => $port->{status} || 'unknown',
            ifAdminStatus => $port->{enabled} ? 'up' : 'down',
            ifSpeed => $port->{speed} || '',
            ifDuplex => $port->{duplex} || '',
            ifType => $port->{type} || '',
            VlanIndex => $port->{vlan} || 0,
        );
        
        push @interfaces, \\%interface;
    }
    
    $self->saveSdnFabricInterface(\\@interfaces) if @interfaces;
}

"""
    
    def _generate_obtain_cdp_lldp(self) -> str:
        """Generate obtainCdpLldp method"""
        return """sub obtainCdpLldp {
    my $self = shift;
    
    $self->{logger}->debug("obtainCdpLldp started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($lldp_cdp, $error) = $api_helper->get_device_lldp_cdp($serial, {timespan => 7200});
    return unless $lldp_cdp;
    
    my @neighbors;
    my $ports = $lldp_cdp->{ports} || {};
    
    foreach my $port_id (keys %$ports) {
        my $port_data = $ports->{$port_id};
        
        # Process LLDP
        if ($port_data->{lldp}) {
            my $lldp = $port_data->{lldp};
            my %neighbor = (
                SdnDeviceDN => $dn,
                ifIndex => $port_id,
                NeighborDeviceID => $lldp->{systemName} || '',
                NeighborPortID => $lldp->{portId} || '',
                NeighborIPAddress => $lldp->{managementAddress} || '',
                Protocol => 'LLDP',
            );
            push @neighbors, \\%neighbor;
        }
        
        # Process CDP
        if ($port_data->{cdp}) {
            my $cdp = $port_data->{cdp};
            my %neighbor = (
                SdnDeviceDN => $dn,
                ifIndex => $port_id,
                NeighborDeviceID => $cdp->{deviceId} || '',
                NeighborPortID => $cdp->{portId} || '',
                NeighborIPAddress => $cdp->{address} || '',
                Protocol => 'CDP',
            );
            push @neighbors, \\%neighbor;
        }
    }
    
    $self->saveSdnLldp(\\@neighbors) if @neighbors;
}

"""
    
    def _generate_obtain_switch_port(self) -> str:
        """Generate obtainSwitchPort method"""
        return """sub obtainSwitchPort {
    my $self = shift;
    
    $self->{logger}->debug("obtainSwitchPort started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($ports, $error) = $api_helper->get_device_switch_ports($serial);
    return unless $ports;
    
    my @switch_ports;
    foreach my $port (@$ports) {
        my %port_config = (
            SdnDeviceDN => $dn,
            ifIndex => $port->{portId} || '',
            VlanIndex => $port->{vlan} || 0,
            PortMode => $port->{type} || 'access',
            AllowedVlans => $port->{allowedVlans} || '',
            POEEnabled => $port->{poeEnabled} ? 1 : 0,
            ifAdminStatus => $port->{enabled} ? 'up' : 'down',
        );
        
        push @switch_ports, \\%port_config;
    }
    
    $self->saveSdnSwitchPortConfig(\\@switch_ports) if @switch_ports;
}

"""
    
    def _generate_obtain_route(self) -> str:
        """Generate obtainRoute method"""
        return """sub obtainRoute {
    my $self = shift;
    
    $self->{logger}->debug("obtainRoute started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($routes, $error) = $api_helper->get_network_appliance_static_routes($network_id);
    return unless $routes;
    
    my @static_routes;
    foreach my $route (@$routes) {
        my %route_info = (
            SdnDeviceDN => $dn,
            RouteCIDR => $route->{subnet} || '',
            RouteNextHop => $route->{gatewayIp} || '',
            RouteName => $route->{name} || '',
            RouteEnabled => $route->{enabled} ? 1 : 0,
        );
        
        push @static_routes, \\%route_info;
    }
    
    $self->saveSdnRoute(\\@static_routes) if @static_routes;
}

"""
    
    def _generate_obtain_wireless(self) -> str:
        """Generate obtainWireless method"""
        return """sub obtainWireless {
    my $self = shift;
    
    $self->{logger}->debug("obtainWireless started");
    my $api_helper = $self->getApiClient();
    my $dn = $self->getDeviceDN();
    my ($org_id, $network_id, $serial) = split('/', $dn);
    
    my ($ssids, $error) = $api_helper->get_network_wireless_ssids($network_id);
    return unless $ssids;
    
    my @wireless_ssids;
    foreach my $ssid (@$ssids) {
        my %ssid_info = (
            SdnDeviceDN => $dn,
            SSID => $ssid->{name} || '',
            SSIDEnabled => $ssid->{enabled} ? 1 : 0,
            SSIDNumber => $ssid->{number} || 0,
            AuthMode => $ssid->{authMode} || '',
            EncryptionMode => $ssid->{encryptionMode} || '',
        );
        
        push @wireless_ssids, \\%ssid_info;
    }
    
    $self->saveSdnWirelessSsid(\\@wireless_ssids) if @wireless_ssids;
}

"""
    
    def _snake_case(self, text: str) -> str:
        """Convert camelCase to snake_case"""
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', text)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    
    def save_modules(self, output_dir: str):
        """Save generated modules to files"""
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        
        # Create subdirectories
        client_dir = output_path / "Client"
        server_dir = output_path / "Server"
        client_dir.mkdir(exist_ok=True)
        server_dir.mkdir(exist_ok=True)
        
        # Generate and save Client module
        client_code = self.generate_client()
        client_file = client_dir / f"{self.vendor_name}_Generated.pm"
        with open(client_file, 'w') as f:
            f.write(client_code)
        print(f"✓ Generated Client module: {client_file}")
        
        # Generate and save Server module
        server_code = self.generate_server()
        server_file = server_dir / f"{self.vendor_name}_Generated.pm"
        with open(server_file, 'w') as f:
            f.write(server_code)
        print(f"✓ Generated Server module: {server_file}")
        
        return client_file, server_file
    
    def print_summary(self, client_file: Path, server_file: Path):
        """Print generation summary"""
        print("\n" + "="*70)
        print("Code Generation Complete")
        print("="*70)
        print(f"\nVendor: {self.vendor_name}")
        print(f"Total Endpoints: {len(self.api_data['endpoints'])}")
        print(f"Mapped Plugins: {len(set(m['plugin'] for m in self.mappings['mappings']))}")
        
        print("\nGenerated Files:")
        print("-"*70)
        
        # Count lines
        with open(client_file, 'r') as f:
            client_lines = len(f.readlines())
        with open(server_file, 'r') as f:
            server_lines = len(f.readlines())
        
        print(f"Client: {client_file}")
        print(f"        {client_lines} lines of code")
        print(f"\nServer: {server_file}")
        print(f"        {server_lines} lines of code")
        print(f"\nTotal: {client_lines + server_lines} lines generated")


def main():
    """Main execution"""
    script_dir = Path(__file__).parent
    plugin_mappings_file = script_dir / "plugin_mappings.json"
    api_data_file = script_dir / "parsed_api.json"
    output_dir = script_dir / "generated"
    
    print("\n🎨 SDN Agent POC - Code Generator")
    print("="*70)
    print(f"Plugin Mappings: {plugin_mappings_file}")
    print(f"API Data: {api_data_file}")
    print(f"Output Directory: {output_dir}")
    
    generator = PerlCodeGenerator(
        str(plugin_mappings_file),
        str(api_data_file)
    )
    
    try:
        # Load data
        generator.load_data()
        
        # Generate and save modules
        client_file, server_file = generator.save_modules(str(output_dir))
        
        # Print summary
        generator.print_summary(client_file, server_file)
        
        print("\n✅ Code generation completed successfully!\n")
        
    except Exception as e:
        print(f"\n❌ Error: {e}\n")
        raise


if __name__ == "__main__":
    main()
